# Generated by Django 5.2.6 on 2025-09-22 20:36

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('embeddings', '0001_initial'),
        ('unipost_image_generator', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneratedImage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('original_text', models.TextField(help_text='Texto do post usado para gerar a imagem', verbose_name='Texto Original')),
                ('generated_prompt', models.TextField(help_text='Prompt criado pelo GPT-4', verbose_name='Prompt Gerado')),
                ('image_path', models.CharField(help_text='Caminho relativo para o arquivo da imagem', max_length=500, verbose_name='Caminho da Imagem')),
                ('dalle_response', models.JSONField(default=dict, help_text='Metadados retornados pela API DALL-E', verbose_name='Resposta DALL-E')),
                ('generation_metadata', models.JSONField(default=dict, help_text='Informações sobre o processo de geração', verbose_name='Metadados de Geração')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('embedding', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generated_images', to='embeddings.embedding', verbose_name='Embedding Relacionado')),
            ],
            options={
                'verbose_name': 'Imagem Gerada',
                'verbose_name_plural': 'Imagens Geradas',
                'ordering': ['-created_at'],
            },
        ),
    ]
