# Generated by Django 5.2.6 on 2025-09-22 20:36

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Embedding',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('origin', models.CharField(choices=[('webscraping', 'WebScraping'), ('generated', 'Generated'), ('business_brain', 'Business Brain')], max_length=20, verbose_name='Origem')),
                ('content', models.TextField(verbose_name='Conteúdo Original')),
                ('title', models.CharField(blank=True, max_length=500, null=True, verbose_name='Título')),
                ('embedding_vector', models.JSONField(verbose_name='Vetor Embedding')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='Metadados')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Embedding',
                'verbose_name_plural': 'Embeddings',
                'ordering': ['-id'],
            },
        ),
    ]
