# Generated by Django 5.2.6 on 2025-09-13 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.BigAutoField(
                    auto_created=True, primary_key=True, serialize=False,
                    verbose_name='ID'
                )),
                ('name', models.CharField(
                    max_length=200, verbose_name='Nome'
                )),
                ('url', models.URLField(verbose_name='URL')),
                ('category', models.CharField(
                    choices=[
                        ('BLOG', 'Blog'), ('ECOMMERCE', 'E-commerce'),
                        ('PORTFOLIO', 'Portfólio'), ('NOTICIAS', 'Notícias'),
                        ('EMPRESA', 'Empresa'), ('EDUCACAO', 'Educação'),
                        ('OUTROS', 'Outros')
                    ],
                    max_length=200, verbose_name='Categoria'
                )),
                ('enable_recursive_crawling', models.BooleanField(
                    default=True,
                    verbose_name='Habilitar crawling recursivo'
                )),
                ('max_depth', models.PositiveIntegerField(
                    default=2,
                    verbose_name='Profundidade máxima de crawling'
                )),
                ('max_pages', models.PositiveIntegerField(
                    default=50,
                    verbose_name='Máximo de páginas para crawl'
                )),
                ('allow_patterns', models.TextField(
                    blank=True,
                    help_text=(
                        'Expressões regulares para URLs que devem ser '
                        'incluídas no crawling'
                    ),
                    null=True,
                    verbose_name='Padrões de URL permitidos (um por linha)'
                )),
                ('deny_patterns', models.TextField(
                    blank=True,
                    help_text=(
                        'Expressões regulares para URLs que devem ser '
                        'excluídas do crawling'
                    ),
                    null=True,
                    verbose_name='Padrões de URL negados (um por linha)'
                )),
                ('content_selectors', models.TextField(
                    blank=True,
                    help_text=(
                        'Seletores CSS específicos para extrair conteúdo '
                        'relevante (um por linha)'
                    ),
                    null=True,
                    verbose_name='Seletores CSS para conteúdo'
                )),
                ('created_at', models.DateTimeField(
                    auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(
                    auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Site',
                'verbose_name_plural': 'Sites',
                'ordering': ['-id'],
            },
        ),
    ]
