# Generated by Django 5.2.6 on 2025-09-22 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='monitored',
            field=models.BooleanField(default=False, help_text='Se True, monitora para novos posts e replica automaticamente. Se False, apenas faz webscraping recursivo.', verbose_name='Monitorar para novos posts'),
        ),
    ]
